# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}

        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Docker login
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: docker build image in github actions
      run: |
        docker build -t mylocalimage . 
        
      - name: docker push to docker hub
      run: |
       docker tag mylocalimage:latest nalapatt123/github-actions:myfirstimagepush
       docker push nalapatt123/github-actions:myfirstimagepush 
        

      
